apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-deployment
  labels:
    app: ssl
spec:
  selector:
    matchLabels:
      app: ssl
  template:
    metadata:
      labels:
        app: ssl
    spec:
      containers:
      - name: pdpro-container
        image: image-registry.openshift-image-registry.svc:5000/[project-name]/ssl:[build-date]
        ports:
        - containerPort: 9080
      imagePullSecrets:
      - name: docker-user-secret
--- 
apiVersion: v1
kind: Service
metadata:
  name: ssl-service
spec:
  selector:
    app: ssl
  ports:
  - protocol: TCP
    port: 9080
---
apiVersion: v1
kind: Route
metadata:
  name: ssl-route
spec:
  to:
    kind: Service
    name: ssl-service
